app.py
from flask import Flask, request, make_response, redirect, render_template, Blueprint, current_app, send_from_directory
from blueprints.logo import logo_bp
import json
import os

app = Flask(__name__)

app.debug = True
app.register_blueprint(logo_bp)

"""
@app.errorhandler(404)
def not_found(error):
    return render_template('404.html', error=error)


@app.errorhandler(500)
def server_error(error):
    return render_template('500.html', error=error)
"""

@app.route('/')
def index():
    user_ip = request.remote_addr

    response = make_response(redirect('/home'))
    response.set_cookie('user_ip', user_ip)

    return response

@app.route('/robots.txt')
def robots():
    robots_txt = "User-agent: *\nDisallow: /private\n"
    response = make_response(robots_txt)
    response.headers["Content-Type"] = "text/plain"
    return response

@app.route('/home')
def hello():
    user_ip = request.cookies.get('user_ip')
    context = {
        'user_ip': user_ip,
        #'todos': todos,
    }
    return render_template('index.html', **context)

@app.route("/buy")
def buy_tickets():
    user_ip = request.cookies.get('user_ip')
    context = {
        'user_ip': user_ip,
        #'todos': todos,
    }
    print(f'Compra iniciada')
    return render_template('buy.html', **context)


@app.route('/infraestructura')
def infraestructura():
    return render_template('infraestructura.html')

@app.route('/construccion')
def construccion():
    return render_template('construccion.html')

@app.route('/consultoria')
def consultoria():
    return render_template('consultoria.html')

@app.route('/tecnologia')
def tecnologia():
    return render_template('tecnologia.html')

@app.route('/servicios')
def servicios():
    return render_template('servicios.html')

@app.route('/contacto')
def contacto():
    return render_template('contacto.html')

@app.route('/nosotros')
def nosotros():
    return render_template('quienes.html')

@app.route('/inspeccion_ditribucion')
def inspeccion_ditribucion():
    return render_template('inspeccion_acu/distribucion.html')

@app.route('/inspeccion_principales')
def inspeccion_principales():
    return render_template('inspeccion_acu/principales.html')

@app.route('/inspeccion_qv')
def inspeccion_qv():
    return render_template('inspeccion_tub/qv.html')

@app.route('/inspeccion_qv360')
def inspeccion_qv360():
    return render_template('inspeccion_tub/qvtressesenta.html')

@app.route('/inspeccion_rx')
def inspeccion_rx():
    return render_template('inspeccion_tub/rx.html')

@app.route('/inspeccion_vsultra')
def inspeccion_vsultra():
    return render_template('inspeccion_tub/vsultra.html')

@app.route('/limpieza_general')
def limpieza_general():
    return render_template('limpieza/general.html')

@app.route('/limpieza_rom')
def limpieza_rom():
    return render_template('limpieza/rom.html')

@app.route('/limpieza_s')
def limpieza_s():
    return render_template('limpieza/s-products.html')

@app.route('/rehabilitacion_equipos')
def rehabilitacion_equipos():
    return render_template('rehabilitacion/equipos.html')

@app.route('/rehabilitacion_materiales')
def rehabilitacion_materiales():
    return render_template('rehabilitacion/materiales.html')

@app.route('/servicios_diseno')
def servicios_diseno():
    return render_template('servicios/diseno.html')

@app.route('/servicios_equipos')
def servicios_equipos():
    return render_template('servicios/equipos.html')

@app.route('/servicios_fugas')
def servicios_fugas():
    return render_template('servicios/fugas.html')

@app.route('/servicios_inspeccion')
def servicios_inspeccion():
    return render_template('servicios/inspeccion.html')

@app.route('/servicios_limpieza')
def servicios_limpieza():
    return render_template('servicios/limpieza_redes.html')

@app.route('/servicios_mapeo')
def servicios_mapeo():
    return render_template('servicios/mapeo.html')

@app.route('/servicios_rehabilitacion')
def servicios_rehabilitacion():
    return render_template('servicios/rehabilitacion_redes.html')

@app.route('/soporte_limpieza')
def soporte_limpieza():
    return render_template('soporte/limpieza.html')

@app.route('/soporte_robotizados')
def soporte_robotizados():
    return render_template('soporte/robotizados.html')

@app.route('/wincan')
def wincan():
    return render_template('wincan.html')

@app.route('/griferia')
def griferia():
    return render_template('productos/griferia.html')

@app.route('/accesorios')
def accesorios():
    return render_template('productos/bano.html')

@app.route('/duchas')
def duchas():
    return render_template('productos/duchas.html')

@app.route('/lavamanos')
def lavamanos():
    return render_template('productos/lavamanos.html')

@app.route('/sanitarios')
def sanitarios():
    return render_template('productos/sanitarios.html')

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host='0.0.0.0', port=port)

blueprints/logo.py
from flask import Blueprint, current_app, send_from_directory

logo_bp = Blueprint('logo', __name__)

@logo_bp.route('/logo.png')
def serve_logo():
    return send_from_directory(current_app.static_folder, 'img/logo.png')

templates/base_const.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %}</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Martian+Mono:wght@100..800&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
  </head>
  <body>
    <!-- Header section start -->
    <header class="header" id="header">
      <nav class="navbar container">
        <section class="navbar__left">
          <a href="{{ url_for('hello') }}" class="brand" >
            <img id="cons-logo" src="{{ url_for('static', filename='img/logo-pacific.png') }}" alt="" />
          </a>
          <div class="burger" id="burger">
            <span class="burger-line"></span>
            <span class="burger-line"></span>
            <span class="burger-line"></span>
          </div>
        </section>
        <section class="navbar__center">
          <span class="overlay"></span>
          <div class="menu" id="menu">
            <div class="menu__header">
              <span class="menu__arrow"
                ><i class="bx bx-chevron-left"></i
              ></span>
              <span class="menu__title"></span>
            </div>
            <ul class="menu__inner" id="construccion">
              
              <li class="menu__item">
                <a href="{{ url_for('construccion') }}" class="menu__link" style="font-size: 16px;">I N I C I O</a>
              </li>
              <li class="menu__item menu__dropdown">
                <a href="#" class="menu__link" style="font-size: 16px;">
                  P R O D U C T O S
                  <i class="fa fa-chevron-right"></i>
                </a>
                <div class="submenu megamenu__text">
                  <div class="submenu__inner">
                    <h4 class="submenu__title">Líneas de Productos</h4>
                    <ul class="submenu__list">
                      <li><a href="{{ url_for('griferia') }}"><span class="icon"><img src="{{ url_for('static', filename='img/icono_submenu.png') }}" alt="Icon">Grifería para Lavamanos</span></a></li>
                      <li><a href="{{ url_for('accesorios') }}"><span class="icon"><img src="{{ url_for('static', filename='img/icono_submenu.png') }}" alt="Icon">Accesorios para Baño</span></a></li>
                      <li><a href="{{ url_for('duchas') }}"><span class="icon"><img src="{{ url_for('static', filename='img/icono_submenu.png') }}" alt="Icon">Duchas y Accesorios</span></a></li>
                      <li><a href="{{ url_for('lavamanos') }}"><span class="icon"><img src="{{ url_for('static', filename='img/icono_submenu.png') }}" alt="Icon">Lavamanos y Accesorios</span></a></li>
                      <li><a href="{{ url_for('sanitarios') }}"><span class="icon"><img src="{{ url_for('static', filename='img/icono_submenu.png') }}" alt="Icon">Sanitarios y Accesorios</span></a></li>
                    </ul>
                  </div>
                </div>
              </li>
              <li class="menu__item">
                <a href="{{ url_for('contacto') }}" class="menu__link" style="font-size: 16px;">C O N T A C T O</a>
              </li>
              <li class="menu__item">
                <a href="{{ url_for('nosotros') }}" class="menu__link" style="font-size: 16px;">N O S O T R O S</a>
              </li>
              <!-- <li class="menu__item">
                <a href="{{ url_for('nosotros') }}" class="menu__link" style="font-size: 16px;">C A T A L O G O</a>
              </li> -->
              <li class="menu__item">
                <a href="{{ url_for('infraestructura') }}" class="menu__link" style="font-size: 12px;">I N F R A E S T R U C T U R A</a>
                <!-- <a href="{{ url_for('infraestructura') }}" class="menu__link">INFRAESTRUCTURA</a> -->
              </li>
            </ul>
          </div>
        </section>
      </nav>
    </header>

    {% block content %}{% endblock %}
       <!-- Footer section start -->
       <div class="footer">
        <div class="row">
          <div class="col-md-4">
            <h3>PRIVACIDAD</h3>
          </div>
          <div class="col-md-4">
            <h3>CONTACTO</h3>
            <a href="mailto:cipacific@cipacifictradinggroup.com"
              >cipacific@cipacifictradinggroup.com</a
            >
            <p><b>CALI</b></p>
            <p>PBX: (57 2) 654 1848</p>
            <p>Comercial: Cel: 310 896 3904 / 311 744 7003</p>
            <p>Administracion: Cel: 310 458 0011</p>
            <p>Direccion: Calle: 15 #31-99</p>
          </div>
          <div class="col-md-4">
            <h4>BOGOTA</h4>
            <p>Cel: 310 3890964</p>
            <p>Autopista Cali- Yumbo -Colombia<br />Bogota</p>
            <p>Cra. 25 No. 70-53</p>
          </div>
        </div>
      </div>
      
      {% block scripts %}{% endblock %}
  </body>
</html>

templates/base_infra.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %}</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Martian+Mono:wght@100..800&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
  </head>
  <body>
    <!-- Header section start -->
    <header class="header" id="header">
      <nav class="navbar container">
        <section class="navbar__left">
          <a href="{{ url_for('hello') }}" class="brand">
            <img src="{{ url_for('static', filename='img/logo-pacific.png') }}" alt="" />
          </a>
          <div class="burger" id="burger">
            <span class="burger-line"></span>
            <span class="burger-line"></span>
            <span class="burger-line"></span>
          </div>
        </section>
        <section class="navbar__center">
          <span class="overlay"></span>
          <div class="menu" id="menu">
            <div class="menu__header">
              <span class="menu__arrow"
                ><i class="bx bx-chevron-left"></i
              ></span>
              <span class="menu__title"></span>
            </div>
            <ul class="menu__inner">
              
              <li class="menu__item">
                <a href="{{ url_for('infraestructura') }}" class="menu__link">I N I C I O</a>
              </li>
              <li class="menu__item menu__dropdown">
                <a href="#" class="menu__link">
                  S E R V I C I O S
                  <i class="fa fa-chevron-right"></i>
                </a>
                <div class="submenu megamenu__text">
                  <div class="submenu__inner">
                    <h4 class="submenu__title">Servicios y consultoría</h4>
                    <ul class="submenu__list">
                      <li><a href="{{ url_for('servicios_inspeccion') }}"><span class="icon"><img src="{{ url_for('static', filename='img/icono_submenu.png') }}" alt="Icon"></span>Inspección y Diagnostico</a></li>
                      <li><a href="{{ url_for('servicios_mapeo') }}"><span class="icon"><img src="{{ url_for('static', filename='img/icono_submenu.png') }}" alt="Icon"></span>Mapeo Subterráneo</a></li>
                      <li><a href="{{ url_for('servicios_limpieza') }}"><span class="icon"><img src="{{ url_for('static', filename='img/icono_submenu.png') }}" alt="Icon"></span>Limpieza de Redes</a></li>
                      <li><a href="{{ url_for('servicios_fugas') }}"><span class="icon"><img src="{{ url_for('static', filename='img/icono_submenu.png') }}" alt="Icon"></span>Detección de Fugas y Reducción de Pérdidas</a></li>
                      <li><a href="{{ url_for('servicios_rehabilitacion') }}"><span class="icon"><img src="{{ url_for('static', filename='img/icono_submenu.png') }}" alt="Icon"></span>Rehabilitación de Redes</a></li>
                      <li><a href="{{ url_for('servicios_diseno') }}"><span class="icon"><img src="{{ url_for('static', filename='img/icono_submenu.png') }}" alt="Icon"></span>Diseño</a></li>
                      <li><a href="{{ url_for('servicios_equipos') }}"><span class="icon"><img src="{{ url_for('static', filename='img/icono_submenu.png') }}" alt="Icon"></span>Equipos y Tecnología</a></li>
                    </ul>
                  </div>
                  <div class="submenu__inner">
                    <h4 class="submenu__title">Equipos de Limpieza para Tuberías y Colectores</h4>
                    <ul class="submenu__list">
                      <li><a href="{{ url_for('limpieza_s') }}"><span class="icon"><img src="{{ url_for('static', filename='img/icono_submenu.png') }}" alt="Icon"></span>S-Products</a></li>
                      <li><a href="{{ url_for('limpieza_rom') }}"><span class="icon"><img src="{{ url_for('static', filename='img/icono_submenu.png') }}" alt="Icon"></span>ROM</a></li>
                      <li><a href="{{ url_for('limpieza_general') }}"><span class="icon"><img src="{{ url_for('static', filename='img/icono_submenu.png') }}" alt="Icon"></span>General</a></li>
                    </ul>
                  </div>
                  <div class="submenu__inner">
                    <h4 class="submenu__title">Software</h4>
                    <ul class="submenu__list">
                      <li><a href="{{ url_for('wincan') }}"><span class="icon"><img src="{{ url_for('static', filename='img/icono_submenu.png') }}" alt="Icon"></span>Software Wincan</a></li>
                    </ul>
                  </div>
                  <div class="submenu__inner">
                    <h4 class="submenu__title">Equipos de Inspección para Tuberías y Colectores</h4>
                    <ul class="submenu__list">
                      <li><a href="{{ url_for('inspeccion_rx') }}"><span class="icon"><img src="{{ url_for('static', filename='img/icono_submenu.png') }}" alt="Icon"></span>RX</a></li>
                      <li><a href="{{ url_for('inspeccion_qv') }}"><span class="icon"><img src="{{ url_for('static', filename='img/icono_submenu.png') }}" alt="Icon"></span>QV</a></li>
                      <li><a href="{{ url_for('inspeccion_vsultra') }}"><span class="icon"><img src="{{ url_for('static', filename='img/icono_submenu.png') }}" alt="Icon"></span>VS Ultra</a></li>
                      <li><a href="{{ url_for('inspeccion_qv360') }}"><span class="icon"><img src="{{ url_for('static', filename='img/icono_submenu.png') }}" alt="Icon"></span>QV360</a></li>
                    </ul>
                  </div>
                  <div class="submenu__inner">
                    <h4 class="submenu__title">Equipos de Inspección para Acueducto</h4>
                    <ul class="submenu__list">
                      <li><a href="{{ url_for('inspeccion_ditribucion') }}"><span class="icon"><img src="{{ url_for('static', filename='img/icono_submenu.png') }}" alt="Icon"></span>Redes de Distribución</a></li>
                      <li><a href="{{ url_for('inspeccion_principales') }}"><span class="icon"><img src="{{ url_for('static', filename='img/icono_submenu.png') }}" alt="Icon"></span>Redes Principales</a></li>
                    </ul>
                  </div>
                  <div class="submenu__inner">
                    <h4 class="submenu__title">Equipos y Materiales de Rehabilitación</h4>
                    <ul class="submenu__list">
                      <li><a href="{{ url_for('rehabilitacion_equipos') }}"><span class="icon"><img src="{{ url_for('static', filename='img/icono_submenu.png') }}" alt="Icon"></span>Equipos de rehabilitación</a></li>
                      <li><a href="{{ url_for('rehabilitacion_materiales') }}"><span class="icon"><img src="{{ url_for('static', filename='img/icono_submenu.png') }}" alt="Icon"></span>Materiales</a></li>
                    </ul>
                  </div>
                  <div class="submenu__inner">
                    <h4 class="submenu__title">Soporte Técnico</h4>
                    <ul class="submenu__list">
                      <li><a href="{{ url_for('soporte_limpieza') }}"><span class="icon"><img src="{{ url_for('static', filename='img/icono_submenu.png') }}" alt="Icon"></span>Equipos de limpieza</a></li>
                      <li><a href="{{ url_for('soporte_robotizados') }}"><span class="icon"><img src="{{ url_for('static', filename='img/icono_submenu.png') }}" alt="Icon"></span>Equipos robotizados</a></li>
                    </ul>
                  </div>
                </div>
              </li>
              <li class="menu__item">
                <a href="{{ url_for('contacto') }}" class="menu__link">C O N T A C T O</a>
              </li>
              <li class="menu__item">
                <a href="{{ url_for('nosotros') }}" class="menu__link">N O S O T R O S</a>
              </li>
              <li class="menu__item">
                <a href="{{ url_for('construccion') }}" class="menu__link">C O N S T R U C C I O N</a>
              </li>
            </ul>
          </div>
        </section>
        <!-- <section class="navbar__right">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Buscar.." />
            <div class="input-group-append">
              <button class="btn btn-secondary" type="button">
                <i class="fa fa-search"></i>
              </button>
            </div>
          </div>
        </section> -->
      </nav>
    </header>

    {% block content %}{% endblock %}

    <!-- Footer section start -->
    <div class="footer">
        <div class="row">
          <div class="col-md-4">
            <h3>PRIVACIDAD</h3>
          </div>
          <div class="col-md-4">
            <h3>CONTACTO</h3>
            <a href="mailto:cipacific@cipacifictradinggroup.com"
              >cipacific@cipacifictradinggroup.com</a
            >
            <p><b>CALI</b></p>
            <p>PBX: (57 2) 654 1848</p>
            <p>Comercial: Cel: 310 896 3904 / 311 744 7003</p>
            <p>Administracion: Cel: 310 458 0011</p>
            <p>Direccion: Calle: 15 #31-99</p>
          </div>
          <div class="col-md-4">
            <h4>BOGOTA</h4>
            <p>Cel: 310 3890964</p>
            <p>Autopista Cali- Yumbo -Colombia<br />Bogota</p>
            <p>Cra. 25 No. 70-53</p>
          </div>
        </div>
      </div>
      
      
      {% block scripts %}{% endblock %}
      <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    <script>
        $(window).on("load resize scroll", function() {
            if ($(window).width() > 768) {
                $(".inspection-sec").each(function() {
                var windowTop = $(window).scrollTop();
                var elementTop = $(this).offset().top;
                var elementHeight = $(this).outerHeight();
                var windowHeight = $(window).height();

                // Calcular la posición relativa del elemento en la ventana
                if (windowTop + windowHeight > elementTop && windowTop < elementTop + elementHeight) {
                    var scrollProgress = (windowTop + windowHeight - elementTop) / (elementHeight + windowHeight);

                    // Ajustar el rango de movimiento de la imagen
                    var leftPosition = (scrollProgress * 90); // Desde -35% hasta 35%

                    // Limitar la posición de la imagen
                    if (leftPosition > 40) {
                    leftPosition = 40;
                    } else if (leftPosition < -35) {
                    leftPosition = -35;
                    }

                    $(this).find(".img-container").css({ left: leftPosition + '%' });
                } else {
                    $(this).find(".img-container").css({ left: 0 });
                }
                });
            } else {
                // En pantallas móviles, resetea la posición de la imagen
                $(".img-container").css({ left: '0' });
            }
            });

    </script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const radioButtons = document.querySelectorAll('.carousel input[type="radio"]');
            const labels = document.querySelectorAll('.carousel__thumbnails label');

            labels.forEach(label => {
                label.addEventListener('click', function(event) {
                    event.preventDefault(); // Evitar el comportamiento predeterminado
                    const radio = document.getElementById(this.getAttribute('for'));
                    radio.checked = true; // Cambiar el estado del radio button
                });
            });
        });
    </script>
  </body>
</html>

templates/index_commets.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Euphoria</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="Euphoria es una agencia especializada en producción audiovisual, marketing digital y desarrollo web. Creamos contenidos innovadores y de calidad para hacer que tu marca destaque en el mundo digital. Contáctanos para conocer cómo podemos ayudarte a impulsar tu presencia en línea.">
  <meta name="author" content="Euphoria">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>

<body>

  <!-- notification for small viewports and landscape oriented smartphones -->
  <div class="device-notification">
    <a class="device-notification--logo" href="/home">
      <img src="{{ url_for('logo.serve_logo') }}" alt="Euphoria company Logo for small devices">
    </a>
    <p class="device-notification--message">Prepárate para vivir una experiencia única en Euphoria. Gira tu dispositivo o consigue una pantalla más grande para disfrutarlo al máximo.</p>
  </div>
  

  <div class="perspective effect-rotate-left">
    <div class="container"><div class="outer-nav--return"></div>
      <div id="viewport" class="l-viewport">
        <div class="l-wrapper">

          <header class="header">
            <a class="header--logo" href="/home">
              <img src="{{ url_for('logo.serve_logo') }}" alt="Euphoria Logo">
            </a>
            <div class="header--nav-toggle">
              <span></span>
            </div>
          </header>
        
          <nav class="l-side-nav">
            <ul class="side-nav">
              <li class="is-active"><span>Home</span></li>
              <li><span>Galería de Arte</span></li>
              <li><span>Nosotros</span></li>
              <li><span>Contacto</span></li>
            </ul>
          </nav>

          <div class="l-main-content main-content">
            <li class="l-section section section--is-active">
              <div class="intro">
                <div class="intro--banner">
                  <h1>Bienvenido a<br>La Revolucion<br>Digital</h1>
                  <button class="cta">Contacto
                    <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 150 118" style="enable-background:new 0 0 150 118;" xml:space="preserve">
                    <g transform="translate(0.000000,118.000000) scale(0.100000,-0.100000)">
                      <path d="M870,1167c-34-17-55-57-46-90c3-15,81-100,194-211l187-185l-565-1c-431,0-571-3-590-13c-55-28-64-94-18-137c21-20,33-20,597-20h575l-192-193C800,103,794,94,849,39c20-20,39-29,61-29c28,0,63,30,298,262c147,144,272,271,279,282c30,51,23,60-219,304C947,1180,926,1196,870,1167z"/>
                    </g>
                    </svg>
                    <span class="btn-background"></span>
                  </button>
                  <img src="{{ url_for('static', filename='img/introduction-visual.png') }}" alt="Astronaut image">
                </div>
                <div class="intro--options">
                  <div>
                    <h3>Creatividad y tecnología fusionadas para impulsar tu éxito digital</h3>
                    <p>Potencia tu estrategia digital y logra tu éxito en línea con nuestra gama completa de servicios. En Euforia creamos productos digitales de vanguardia abarcan fotografía y videografía profesional, diseño web cautivador, marketing digital efectivo y gestión de redes sociales. ¡Descubre una nueva forma de romper tus barreras!</p>
                  </div>
                </div>
              </div>
            </li>
            <li class="l-section section">
              <div class="work">
                <h2>Ver Portafolio</h2>
                <div class="work--lockup">
                  <ul class="slider">
                    <li class="slider--item slider--item-center">
                      <a href="https://drive.google.com/file/d/1w8AvEx9KbXRrujOlXVtmoE_NJedQn6sF/view?usp=sharing">
                        <div class="slider--item-image">
                          <img src="{{ url_for('static', filename='img/diamond.jpg') }}" alt="Imagen que ilustra los casos de exito">
                        </div>
                      </a>
                    </li>
                  </ul>
              </div>
            </li>
            <li class="l-section section">
              <div class="about">
                <div class="about--banner">
                  <h2>Creemos en<br>Nuestro Poder<br>de Alquimia</h2>
                  <img src="{{ url_for('static', filename='img/about-visual.png') }}" alt="About Us image">
                </div>
              </div>
            </li>
            <li class="l-section section">
              <div class="contact">
                <div class="contact--lockup">
                  <div class="modal">
                    <div class="modal--information">
                      <p>Calle 27 # 41 - 86, Medellín, Colombia</p>
                      <p>Cra 1B # 54 A - 50, Cali, Colombia</p>
                      <a href="https://www.instagram.com/EuphoriaCreativeLab/">@euphoria_artlab</a> 
                      <a href="tel:+573147566165">+57 321 580 48 19</a>
                      <a href="tel:+573147566165">+57 314 756 61 65</a>
                    </div>
                    <ul class="modal--options">
                      <li><a href="tel:+573215804819">Contáctanos</a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </li>
          </div>
        </div>
      </div>
      <div>
        <footer class="footer-container">
          <a class="footer--logo" href="/home">
            <img src="{{ url_for('logo.serve_logo') }}" alt="Euphoria Logo">
          </a>
          <div class="footer-text">
            <h5>Todos los derechos reservados.</h5>
          </div>
        </footer>
      </div>
    </div>
    <ul class="outer-nav">
      <li class="is-active">Home</li>
      <li>Galería</li>
      <li>Nosotros</li>
      <li>Contacto</li>
    </ul>
  </div>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
  <script>window.jQuery || document.write("<script src='{{ url_for('static', filename='js/vendor/jquery-2.2.4.min.js') }}'><\/script>")</script>
  <script src="{{ url_for('static', filename='js/functions-min.js') }}"></script>
</body>
</html>